import {calculate} from './rb-calc.mjs';
const $=s=>document.querySelector(s),key='mnp-rb-pilot-v1',fields=['quantity','stock','perFg','yield','weight','setup','joint','scrap','batch','increment'];
const products=[{id:'DEMO-RB-001',name:'ชิ้นส่วนยางตัวอย่าง A',formula:'DEMO-COMPOUND-A',perFg:2,yield:10,weight:100},{id:'DEMO-RB-002',name:'ชิ้นส่วนยางตัวอย่าง B',formula:'DEMO-COMPOUND-B',perFg:1,yield:5,weight:250}];
let current=null,history=[];const fmt=v=>v.toLocaleString('th-TH',{maximumFractionDigits:4});
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))history=data}catch{$('#feedback').textContent='อ่านประวัติไม่ได้ ข้อมูลเดิมยังไม่ถูกเขียนทับ'}
for(const p of products){const o=document.createElement('option');o.value=p.id;o.textContent=p.id+' — '+p.name;$('#product').append(o)}
function invalidate(){current=null;$('#save').disabled=true;$('#print').disabled=true;$('#result').textContent='ข้อมูลเปลี่ยนแล้ว กรุณาคำนวณใหม่'}
$('#plan').addEventListener('input',invalidate);$('#product').onchange=()=>{const p=products.find(p=>p.id==$('#product').value);for(const k of ['perFg','yield','weight'])$('#'+k).value=p[k];invalidate()};
function show(record){$('#result').replaceChildren();const title=document.createElement('p');title.textContent=record.reference+' / '+record.product.id+' / '+record.product.formula;$('#result').append(title);const table=document.createElement('table');for(const [key,label] of Object.entries({pieces:'ต้องการชิ้นส่วน (ชิ้น)',required:'RB ที่ต้องใช้ก่อนหักคลัง (เส้น)',produce:'RB ที่ต้องผลิต (เส้น)',net:'น้ำหนักสุทธิ (กก.)',setup:'เผื่อแกะหัว (กก.)',joint:'เผื่อข้อต่อ (กก.)',scrap:'เผื่อเสียทั่วไป (กก.)',total:'น้ำหนักรวม (กก.)',rounded:'น้ำหนักปัดตามขั้นต่ำ (กก.)',batches:'เทียบจำนวนโม่ — ไม่ได้ปัดโม่เต็ม',extra:'น้ำหนักเพิ่มจากการปัด (กก.)'})){const tr=table.insertRow();tr.insertCell().textContent=label;tr.insertCell().textContent=fmt(record.result[key])}$('#result').append(table)}
$('#plan').onsubmit=e=>{e.preventDefault();try{const inputs=Object.fromEntries(fields.map(k=>[k,Number($('#'+k).value)]));current={id:crypto.randomUUID(),reference:$('#reference').value.trim(),product:{...products.find(p=>p.id==$('#product').value)},inputs,result:calculate(inputs),created:new Date().toISOString(),ruleVersion:'trial-0.1'};if(!current.reference)throw Error('กรุณาระบุออเดอร์');show(current);$('#save').disabled=false;$('#print').disabled=false;$('#feedback').textContent='คำนวณแล้ว — ยังไม่จองหรือตัดสต็อก'}catch(err){invalidate();$('#feedback').textContent=err.message}};
$('#save').onclick=()=>{if(!current)return;try{const next=[current,...history];localStorage.setItem(key,JSON.stringify(next));history=next;$('#save').disabled=true;$('#feedback').textContent='บันทึกฉบับทดลองแล้ว';renderHistory()}catch{$('#feedback').textContent='บันทึกไม่สำเร็จ กรุณาตรวจพื้นที่ Browser'}};
$('#print').onclick=()=>window.print();function renderHistory(){$('#history').replaceChildren();for(const record of history){const button=document.createElement('button');button.textContent=record.reference+' • '+record.product.id+' • '+new Date(record.created).toLocaleString('th-TH');button.onclick=()=>{invalidate();show(record);$('#print').disabled=false;$('#feedback').textContent='กำลังดูเอกสารย้อนหลัง '+record.ruleVersion};$('#history').append(button)}}renderHistory();
